### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by nok** [cstrobbe/languagelearning#1]
Yeah, great site! 👍 

But there are some broken links:

`410`: https://taskbasedlanguageteaching.wordpress.com/2014/06/04/a-brief-history-of-language-methodologies-and-the-theoretical-rationale-for-task-based-language-teaching/
`404`: http://www.lindsaydoeslanguages.com/blog/
`404`: http://www.stormkingpress.com/Storm_King_Press/Storm_King_Press___How_To_Learn_A_Foreign_Language.html
`301`: http://www.simonandschuster.com:80/books/Babel-No-More/Michael-Erard/9781451628265
`404`: http://www.tarcherbooks.net/bad-at-math-you-can-achieve-a-mind-for-numbers/
`404`: http://www-tcall.tamu.edu/research/nso/ss/ss_c.html
`404`: http://jillrobbins.com/n/wp-content/uploads/2011/12/strategylist.pdf
`404`: http://polyglotberlin.com/howto
`404`: http://celeration.org/learning-area/jptc-journal-archive/
`404`: http://celeration.org/learning-area/the-standard-celeration-chart/
`403`: http://fluency.org/
`404`: http://fluency.org/17201.html
`404`: http://fluency.org/17222.html
`404`: http://fluency.org/17243.html
`404`: http://fluency.org/17285.html
`404`: http://fluency.org/43901.html
`404`: http://celeration.org/wp-content/uploads/2015/06/JPTC_V06.03_01.pdf
`404`: http://celeration.org/wp-content/uploads/2015/06/JPTC_V07.02_12.pdf
`404`: http://celeration.org/wp-content/uploads/2015/06/JPTC_V06.03_00.pdf
`404`: http://celeration.org/about-scs/
`404`: http://www.collinslanguage.com/advanced-learners-english-dictionary-fifth-edition-9780007210138?pageid=55
`500`: http://comet.cls.yale.edu/chineseusagedictionary/ ?
`404`: http://celeration.org/wp-content/uploads/2015/06/JPTC_V14.01_07.pdf
`404`: http://www.learnbritishenglish.co.uk/english-lessons-on-skype-with-native-teacher/
`404`: http://www.mcgraw-hill.co.uk/html/0071457089.html
`404`: http://www.physiologus.de/fischhaut.htm
`Timeout`: http://hua.umf.maine.edu/China/diction.html
`Timeout`: http://discovermandarin.com/

🖖

**Comment by cstrobbe** [comment]
Thanks for the list of broken links. The updated links should go live in the next few days. 
(Did you use a specific tools to generate this list?)

**Comment by cstrobbe** [comment]
The reported links have all been checked and where necessary removed or replaced.
